CREATE TABLE `candidatos_tse` (
	`id` int AUTO_INCREMENT NOT NULL,
	`dtGeracao` varchar(20),
	`anoEleicao` int NOT NULL,
	`cdTipoEleicao` varchar(10),
	`nmTipoEleicao` varchar(50),
	`nrTurno` int DEFAULT 1,
	`cdEleicao` varchar(20),
	`dsEleicao` varchar(100),
	`sgUf` varchar(2),
	`sgUe` varchar(10),
	`nmUe` varchar(100),
	`cdCargo` varchar(10),
	`dsCargo` varchar(50),
	`sqCandidato` varchar(20),
	`nrCandidato` int,
	`nmCandidato` varchar(200),
	`nmUrna` varchar(100),
	`nmSocial` varchar(200),
	`nrCpf` varchar(15),
	`nmEmail` varchar(200),
	`cdSituacaoCandidatura` varchar(10),
	`dsSituacaoCandidatura` varchar(50),
	`cdDetalhesSituacaoCand` varchar(10),
	`dsDetalhesSituacaoCand` varchar(100),
	`tpAgremiacao` varchar(50),
	`nrPartido` int,
	`sgPartido` varchar(20),
	`nmPartido` varchar(200),
	`sqColigacao` varchar(20),
	`nmColigacao` varchar(200),
	`dsComposicaoColigacao` text,
	`cdNacionalidade` varchar(10),
	`dsNacionalidade` varchar(50),
	`sgUfNascimento` varchar(2),
	`cdMunicipioNascimento` varchar(10),
	`nmMunicipioNascimento` varchar(100),
	`dtNascimento` varchar(20),
	`nrIdadeDataPosse` int,
	`nrTituloEleitoral` varchar(20),
	`cdGenero` varchar(5),
	`dsGenero` varchar(20),
	`cdGrauInstrucao` varchar(5),
	`dsGrauInstrucao` varchar(50),
	`cdEstadoCivil` varchar(5),
	`dsEstadoCivil` varchar(30),
	`cdCorRaca` varchar(5),
	`dsCorRaca` varchar(30),
	`cdOcupacao` varchar(10),
	`dsOcupacao` varchar(100),
	`vrDespesaMaxCampanha` decimal(15,2),
	`cdSitTotTurno` varchar(10),
	`dsSitTotTurno` varchar(50),
	`stReeleicao` varchar(5),
	`stDeclaraBens` varchar(5),
	`nrProtocoloCandidatura` varchar(30),
	`nrProcesso` varchar(30),
	`importacaoId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `candidatos_tse_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `coligacoes_tse` (
	`id` int AUTO_INCREMENT NOT NULL,
	`dtGeracao` varchar(20),
	`anoEleicao` int NOT NULL,
	`cdTipoEleicao` varchar(10),
	`nmTipoEleicao` varchar(50),
	`nrTurno` int DEFAULT 1,
	`cdEleicao` varchar(20),
	`dsEleicao` varchar(100),
	`sgUf` varchar(2),
	`sgUe` varchar(10),
	`nmUe` varchar(100),
	`cdCargo` varchar(10),
	`dsCargo` varchar(50),
	`tpAgremiacao` varchar(50),
	`sqColigacao` varchar(20),
	`nmColigacao` varchar(200),
	`dsComposicaoColigacao` text,
	`stColigacao` varchar(20),
	`importacaoId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `coligacoes_tse_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `eleitorado_tse` (
	`id` int AUTO_INCREMENT NOT NULL,
	`dtGeracao` varchar(20),
	`anoEleicao` int NOT NULL,
	`sgUf` varchar(2) DEFAULT 'RO',
	`cdMunicipio` varchar(10),
	`nmMunicipio` varchar(100),
	`cdMrc` varchar(10),
	`nmMrc` varchar(100),
	`nrZona` int,
	`cdGenero` varchar(5),
	`dsGenero` varchar(20),
	`cdEstadoCivil` varchar(5),
	`dsEstadoCivil` varchar(30),
	`cdFaixaEtaria` varchar(10),
	`dsFaixaEtaria` varchar(30),
	`cdGrauEscolaridade` varchar(5),
	`dsGrauEscolaridade` varchar(50),
	`qtEleitoresPerfilBiometrico` int DEFAULT 0,
	`qtEleitoresPerfilDeficiencia` int DEFAULT 0,
	`qtEleitoresPerfilNomeSocial` int DEFAULT 0,
	`qtEleitoresPerfil` int DEFAULT 0,
	`importacaoId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `eleitorado_tse_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `partidos_tse` (
	`id` int AUTO_INCREMENT NOT NULL,
	`dtGeracao` varchar(20),
	`anoEleicao` int NOT NULL,
	`sgUf` varchar(2),
	`tpAgremiacao` varchar(50),
	`nrPartido` int,
	`sgPartido` varchar(20),
	`nmPartido` varchar(200),
	`sqPartido` varchar(20),
	`nrCnpj` varchar(20),
	`dtCriacaoPartido` varchar(20),
	`dtRegistroTse` varchar(20),
	`dtExtincaoPartido` varchar(20),
	`importacaoId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `partidos_tse_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
ALTER TABLE `importacoes` MODIFY COLUMN `tipoDataset` enum('eleitorado','candidatos','partidos','coligacoes','resultados','votos_nulos_brancos') NOT NULL;--> statement-breakpoint
ALTER TABLE `municipios` ADD `codigoTse` varchar(10);--> statement-breakpoint
ALTER TABLE `candidatos_tse` ADD CONSTRAINT `candidatos_tse_importacaoId_importacoes_id_fk` FOREIGN KEY (`importacaoId`) REFERENCES `importacoes`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `coligacoes_tse` ADD CONSTRAINT `coligacoes_tse_importacaoId_importacoes_id_fk` FOREIGN KEY (`importacaoId`) REFERENCES `importacoes`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `eleitorado_tse` ADD CONSTRAINT `eleitorado_tse_importacaoId_importacoes_id_fk` FOREIGN KEY (`importacaoId`) REFERENCES `importacoes`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `partidos_tse` ADD CONSTRAINT `partidos_tse_importacaoId_importacoes_id_fk` FOREIGN KEY (`importacaoId`) REFERENCES `importacoes`(`id`) ON DELETE no action ON UPDATE no action;